const nftAttributes = {
  background: {
    "black white": 18,
    "green": 18,
    "grey": 2,
    "light blue": 54,
    "pink purple": 54,
    "pink": 54,
    "purple": 54,
    "red brown": 22,
    "yellow orange": 4,
    "yellow": 2
  },
  wing: {
    "gold": 4,
    "none": 54,
    "silver": 18,
    "white": 4
  },
  base: {
    "brown": 54,
    "dark grey": 4,
    "gold": 2,
    "silver": 54
  },
  body: {
    "black gold robe": 2,
    "black skeleton": 18,
    "black suspenders": 22,
    "black white soccer jeeb": 18,
    "black white tux": 18,
    "black yellow samurai": 22,
    "blue dark blue emperor robe": 22,
    "blue gold emperor robe": 18,
    "blue gold robot": 54,
    "blue grey samurai": 22,
    "blue grey suspenders": 22,
    "blue jacket": 22,
    "blue red suit": 22,
    "blue robe": 54,
    "blue skeleton": 54,
    "blue soccer jeeb": 54,
    "blue tux": 54,
    "brown grey suit": 54,
    "brown jacket": 54,
    "brown red jacket": 18,
    "brown red samurai": 54,
    "checkered suit": 4,
    "dark blue tux": 22,
    "dark gray shirt": 22,
    "gray purple robot": 54,
    "grey black samurai": 18,
    "grey blue suit": 54,
    "grey jacket": 18,
    "grey red emperor robe": 22,
    "grey suit camouflage": 54,
    "grey suspenders": 54,
    "lavender shirt": 18,
    "light blue suit": 54,
    "light grey robot": 54,
    "none": 54,
    "pink robe": 54,
    "pink tan robe": 18,
    "purple blue shirt": 4,
    "purple suspenders": 18,
    "purple yellow emperor robe": 4,
    "red basketball jersey": 4,
    "red black basketball jersey": 2,
    "red black samurai": 4,
    "red blue emperor robe": 18,
    "red blue suit": 22,
    "red gold emperor robe": 2,
    "red gold robe": 4,
    "red skeleton": 54,
    "red suspenders": 18,
    "red tie checkered suit": 2,
    "red white tux": 2,
    "royal blue suspenders": 54,
    "silver black suit": 54,
    "silver robe": 22,
    "silver suit camouflage": 18,
    "sky blue shirt": 22,
    "sky blue suspenders": 54,
    "tan suspenders": 54,
    "white black soccer jeeb": 22,
    "white suspenders": 2,
    "yellow purple jacket": 4,
    "yellow purple robot": 18,
    "yellow shirt": 18,
    "yellow soccer jeeb": 54,
    "yellow suspenders": 4
  },
  accessory: {
    "gold chain": 2,
    "none": 54,
    "silver chain": 4
  },
  eyes: {
    "black blue ski": 22,
    "black eyeglasses": 54,
    "black green ski": 54,
    "black pruple ski": 22,
    "black rainbow ski": 2,
    "black red ski": 4,
    "black ski": 18,
    "black sunglasses": 54,
    "black white ski": 18,
    "black yellow frame eyeglasses": 2,
    "black yellow ski": 22,
    "blue eyeglasses": 54,
    "blue sunglasses": 22,
    "eyepatch": 54,
    "none": 54,
    "red eyeglasses": 18,
    "red sunglasses": 18,
    "sunglasses yellow": 2,
    "tan sunglasses": 22,
    "yellow black frame eyeglasses": 2
  },
  head: {
    "black golf visor": 54,
    "black yellow baseball cap": 54,
    "blue baseball cap": 54,
    "blue camouflage baseball cap": 54,
    "blue golf visor": 54,
    "brown baseball cap": 54,
    "crown": 2,
    "gold golf visor": 2,
    "green camouflage baseball cap": 54,
    "green camouflage golf visor": 22,
    "green golf visor": 22,
    "light grey golf visor": 4,
    "none": 54,
    "orange golf visor": 22,
    "red golf visor": 18,
    "silver camouflage baseball cap": 22,
    "silver camouflage golf visor": 18,
    "tan golf visor": 54,
    "viking": 2
  },
  earring: {
    "black hoop": 2,
    "blue hoop": 54,
    "blue hue diamond": 18,
    "gold hoop": 2,
    "green diamond": 4,
    "light green diamond": 2,
    "none": 54,
    "purple diamond": 22,
    "red hoop": 54,
    "silver hoop": 18,
    "white diamond": 18
  },
  hand: {
    "blue spear": 54,
    "cash": 22,
    "champagne": 54,
    "cigar": 18,
    "gun": 2,
    "liquor": 4,
    "microphone": 54,
    "none": 54,
    "rabbit": 4,
    "red spear": 54,
    "scepter": 18,
    "skull": 2
  }
};

export default nftAttributes;