/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC721Staking__factory } from "./ERC721Staking__factory";
export { NFTContract__factory } from "./NFTContract__factory";
